import json

from colorama import Fore

from petrabot.reasoning.constants import REACT_SYSTEM_PROMPT
from petrabot.tools.tool import Tool, validate_arguments
from petrabot.utils.agent_utils import ChatHistory, build_prompt_structure, update_chat_history
from petrabot.utils.completions import create_chat_completion
from petrabot.utils.constants import BASE_SYSTEM_PROMPT
from petrabot.reasoning.types import LLMMetadata
from petrabot.utils.extraction import extract_tag_content


class ReactAgent:
    """
    A class that represents an agent using the ReAct logic that interacts with tools to process
    user inputs, make decisions, and execute tool calls. The agent can run interactive sessions,
    collect tool signatures, and process multiple tool calls in a given round of interaction.

    Attributes:
        llm_metadata (dict): Metadata for LLM client used to handle model-based completions.
        tools (list[Tool]): A list of Tool instances available for execution.
        tools_dict (dict): A dictionary mapping tool names to their corresponding Tool instances.
    """
    def __init__(
        self,
        llm_metadata: LLMMetadata,
        tools: Tool | list[Tool],
        system_prompt: str = BASE_SYSTEM_PROMPT,
    ) -> None:
        self.llm_metadata = llm_metadata
        self.system_prompt = system_prompt
        self.tools = tools if isinstance(tools, list) else [tools]
        self.tools_dict = {tool.name: tool for tool in self.tools}
    
    def add_tool_signatures(self) -> str:
        """
        Collects the function signatures of all available tools.

        Returns:
            str: A concatenated string of all tool function signatures in JSON format.
        """
        return "".join([tool.fn_signature for tool in self.tools])
    
    def process_tool_calls(self, tool_calls_content: list) -> dict:
        """
        Processes each tool call, validates arguments, executes the tools, and collects results.

        Args:
            tool_calls_content (list): List of strings, each representing a tool call in JSON format.

        Returns:
            dict: A dictionary where the keys are tool call IDs and values are the results from the tools.
        """
        observations = {}
        for tool_call_str in tool_calls_content:
            tool_call = json.loads(tool_call_str)
            tool_name = tool_call["name"]
            tool = self.tools_dict[tool_name]

            print(Fore.GREEN + f"\nUsing Tool: {tool_name}")

            # Validate and execute the tool call
            validated_tool_call = validate_arguments(
                tool_call, json.loads(tool.fn_signature)
            )
            print(Fore.GREEN + f"\nTool call dict: \n{validated_tool_call}")

            result = tool.run(**validated_tool_call["arguments"])
            print(Fore.GREEN + f"\nTool result: \n{result}")

            # Store the result using the tool call ID
            observations[validated_tool_call["id"]] = result

        return observations


    def run(
        self,
        user_msg: str,
        chat_history: ChatHistory,
        max_rounds: int = 3,
    ) -> str:
        """
        Executes a user interaction session, where the agent processes user input, generates responses,
        handles tool calls, and updates chat history until a final response is ready or the maximum
        number of rounds is reached.

        Args:
            user_msg (str): The user's input message to start the interaction.
            max_rounds (int, optional): Maximum number of interaction rounds the agent should perform. Default is 10.

        Returns:
            str: The final response generated by the agent after processing user input and any tool calls.
        """
        if self.tools:
            self.system_prompt += (
                "\n" + REACT_SYSTEM_PROMPT % self.add_tool_signatures()
            )
        
        update_chat_history(
            chat_history,
            self.system_prompt
            , "user"
        )
        
        update_chat_history(chat_history, user_msg, "user") 

        if self.tools:
            # Run the ReAct loop for max_rounds
            for _ in range(max_rounds):

                completion = create_chat_completion(self.llm_metadata, self.system_prompt, chat_history)
                print(Fore.YELLOW + f"\nCompletion: {completion}")
                response = extract_tag_content(str(completion), "response")
                if response.found:
                    return response.content[0]

                thought = extract_tag_content(str(completion), "thought")
                if thought.found:
                    tool_calls = extract_tag_content(str(completion), "tool_call")

                    update_chat_history(chat_history, completion, "model")

                    print(Fore.MAGENTA + f"\nThought: {thought.content}")

                    if tool_calls.found:
                        observations = self.process_tool_calls(tool_calls.content)
                        print(Fore.BLUE + f"\nObservations: {observations}")
                        update_chat_history(chat_history, f"{observations}", "user")

        return create_chat_completion(self.llm_metadata, self.system_prompt, chat_history)